// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fKFpbA8pOgJJwOODQ7HCUzcZZLTsiHI',
    appId: '1:306674807864:web:c220e0191a4103bb6362cd',
    messagingSenderId: '306674807864',
    projectId: 'persuasive-ego-377212',
    authDomain: 'persuasive-ego-377212.firebaseapp.com',
    storageBucket: 'persuasive-ego-377212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFg6vVUdU9agAr9BahpkrEXQ2F-uy6PF0',
    appId: '1:306674807864:android:061174ab4fd1fc1d6362cd',
    messagingSenderId: '306674807864',
    projectId: 'persuasive-ego-377212',
    storageBucket: 'persuasive-ego-377212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVWQiNm8ucFXt8ALsgbIVjUDG59KOXKk',
    appId: '1:306674807864:ios:1404287d52dee6f56362cd',
    messagingSenderId: '306674807864',
    projectId: 'persuasive-ego-377212',
    storageBucket: 'persuasive-ego-377212.appspot.com',
    iosBundleId: 'com.example.cabeasy',
  );
}
